# Generated by Django 4.1.2 on 2023-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_ksiazka_contributedyby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='imie',
            field=models.CharField(max_length=30),
        ),
    ]
